# Generated by Django 4.0.4 on 2022-05-28 20:09

import atm.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс доступної готівки в банкоматі')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Номер карти')),
                ('currency', models.CharField(choices=[('UAH', 'Гривня'), ('USD', 'Долар США'), ('EUR', 'Євро')], default='UAH', max_length=3, verbose_name='Валюта карти')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс карти')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Номер карти')),
                ('iban', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Номер рахунку IBAN')),
                ('password', models.CharField(default='0000', max_length=4, verbose_name='PIN-код')),
                ('last_name', models.CharField(max_length=30, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=30, verbose_name="Ім'я")),
                ('phone_number', models.CharField(max_length=13, verbose_name='Фінансовий номер телефону')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата відкриття рахунку')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення даних')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm.atm')),
                ('card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='atm.card')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', atm.models.UserManager()),
            ],
        ),
    ]
